### PR TITLE
fix: eslint max depth warnings

### LINKED ISSUE #1249: Resolve eslint `max-depth` warnings
### Describe what should be investigated or refactored

ESlint has several warnings for [max-depth](https://eslint.org/docs/latest/rules/max-depth) violations across the codebase. Resolve these warnings.

### Definition of Done

* There are zero eslint warnings for `max-depth`
* `max-depth` is set to `error` from `warn` in `.eslintrc.json`

### Additional context

Run the linter with `npm format:check`

### PR DESCRIPTION
**Pull request by tamirazrab**
## Description
Fixes eslint `max-depth` warnings in different files. 

Left out` helper.ts` purposely not sure how to remove nesting there.

## Related Issue

Fixes #1249 

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging
- [X] Unit, [Journey](https://github.com/defenseunicorns/pepr/tree/main/journey), [E2E Tests](https://github.com/defenseunicorns/pepr-excellent-examples), [docs](https://github.com/defenseunicorns/pepr/tree/main/docs), [adr](https://github.com/defenseunicorns/pepr/tree/main/adr) added or updated as needed
- [X] [Contributor Guide Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request) followed

### CODE REVIEW

**Comment by cmwylie19** [comment]
We need to hold off on this PR until our release next week. Thank you for your contribution!

File: src/cli/init/index.ts [hunk 1]
```diff
@@ -86,13 +86,13 @@ export default function (program: RootCmd) {
...
-            } catch (e) {
-              // vscode not found, do nothing
-            }
+            // try {
+            execSync("code .", {
+              stdio: "inherit",
+            });
+            // } catch (e) {
+            // vscode not found, do nothing
+            // }
```
Comment (samayer12) [inline src/cli/init/index.ts]: We should double-check the error behavior here when `code` is not a binary on the system

File: src/lib/validate-processor.ts [hunk 2]
```diff
@@ -59,12 +59,10 @@ export async function validateProcessor(
...
-        if (resp.statusCode || resp.statusMessage) {
-          localResponse.status = {
-            code: resp.statusCode || 400,
-            message: resp.statusMessage || `Validation failed for ${name}`,
-          };
-        }
+        localResponse.status = {
+          code: resp.statusCode || 400,
+          message: resp.statusMessage || `Validation failed for ${name}`,
+        };
```
Comment (samayer12) [inline src/lib/validate-processor.ts:65]: What happens if `resp` does not include either property but is otherwise okay? Is that possible? Without the conditional it looks like we'd say `400` and `Validation failed` as a fallback, which seems reasonable.  We should look into that before merging.

**Review by samayer12 — CHANGES_REQUESTED** [review]
Linter warnings are resolved (aside from `helper.ts` as noted), thank you! Left a couple comments for questions that the maintainers can consider prior to merging.

**Comment by cmwylie19** [comment]
can you please run `npm run format:fix` to try and fix the formatting issues? @tamirazrab

**Comment by tamirazrab** [comment]
> can you please run `npm run format:fix` to try and fix the formatting issues? @tamirazrab

Yes I did, sorry for delay, most warning aren't related to `max-depth` other than `pepr/src/lib/helpers.ts` which I'm not really sure how to proceed refactoring it.

**Comment by samayer12** [comment]
@tamirazrab, thanks for doing the bulk of the work resolving the max-depth warnings! I'm gonna knock out the last few things and update the branch for us since we've had several changes over the past few weeks.

File: src/cli/init/index.ts (hunk 1 above)
Comment (samayer12) [reply src/cli/init/index.ts]: This is required, otherwise we fail the test and log an exception.

**Comment by samayer12** [comment]
There are broader issues with test-coverage in the refactored files that we already know about, accepting the small overall decrease to gain linter resolutions.
