### PR TITLE
fix: reconcile queues scrambling Action callbacks

### LINKED ISSUE #1115: Troubleshoot pepr v0.35.0 not reconciling UDS Package
### Environment
Device and OS:  Ubuntu 24.04
Kubernetes distro being used:  (K3d) v1.29.6+k3s2

### Steps to reproduce
1. Run `uds run slim-dev`
2. Watch for (intermittent?) timeout trying to deploy keycloak package.

### Expected result
Successful deployment of UDS package for keycloak

### Actual Result
Timeout waiting for UDS Package for keycloak to come up.
image

### PR DESCRIPTION
**Pull request by btlghrants**
## Description

When running `uds run slim-dev` (and friends) against pepr@0.35.0, then UDS Package CRs will occasionally (approx. 50% of runs) _not_ complete deployment.

Description / analysis / troubleshooting steps detailed in related issue.

This PR is intended to fix the erroneous behavior.

## Related Issue

Fixes #1115 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging
- [ ] Unit, [Journey](https://github.com/defenseunicorns/pepr/tree/main/journey), [E2E Tests](https://github.com/defenseunicorns/pepr-excellent-examples), [docs](https://github.com/defenseunicorns/pepr/tree/main/docs), [adr](https://github.com/defenseunicorns/pepr/tree/main/adr) added or updated as needed
- [x] [Contributor Guide Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request) followed

### CODE REVIEW

File: src/lib/queue.ts [hunk 1]
```diff
@@ -15,29 +19,51 @@ type QueueItem<K extends KubernetesObject> = {
...
+  enqueue(item: K, phase: WatchPhase, reconcile: WatchCallback) {
+    const note = {
+      queue: this.label(),
+      item: {
+        name: item.metadata?.name,
+        namespace: item.metadata?.namespace,
+        resourceVersion: item.metadata?.resourceVersion,
+      },
+    };
+    Log.info(note, "Enqueueing");
```
Comment (btlghrants) [inline src/lib/queue.ts]:
```suggestion
    Log.debug(note, "Enqueueing");
```

File: src/lib/queue.ts [hunk 2]
```diff
@@ -68,16 +94,25 @@ export class Queue<K extends KubernetesObject> {
...
-      }
+      const note = {
+        queue: this.label(),
+        item: {
+          name: element.item.metadata?.name,
+          namespace: element.item.metadata?.namespace,
+          resourceVersion: element.item.metadata?.resourceVersion,
+        },
+      };
+      Log.info(note, "Reconciling");
```
Comment (btlghrants) [inline src/lib/queue.ts]:
```suggestion
      Log.debug(note, "Reconciling");
```

File: src/lib/queue.ts [hunk 3]
```diff
@@ -68,16 +94,25 @@ export class Queue<K extends KubernetesObject> {
...
+      await element.callback(element.item, element.phase);
+      Log.info(note, "Reconciled");
```
Comment (btlghrants) [inline src/lib/queue.ts]:
```suggestion
      Log.debug(note, "Reconciled");
```

File: src/lib/queue.ts (hunk 2 above)
Comment (cmwylie19) [reply src/lib/queue.ts]: This is because if they are reconciling against secrets, they will be exposed (with b64, of course) in controller logs and there will be no way of turning them off

File: src/lib/queue.ts (hunk 3 above)
Comment (cmwylie19) [reply src/lib/queue.ts]: This is because if they are reconciling against secrets, they will be exposed (with b64, of course) in controller logs and there will be no way of turning them off

File: src/lib/watch-processor.ts [hunk 4]
```diff
@@ -32,6 +32,14 @@ export function queueRecordKey(obj: KubernetesObject) {
   return strat === "singular" ? `${kind}/${ns}` : `${kind}/${name}/${ns}`;
```
Comment (cmwylie19) [inline src/lib/watch-processor.ts:32]:
```suggestion
  return strat === "singular" ? `${kind}/${ns}` : `${kind}/${name}/${ns}`;
```

This is technically a new strategy, we can protect users by having a strategy for just `kind`, allowing them to choose.

Comment (btlghrants) [reply src/lib/watch-processor.ts:32]: Yep, currently thinking "kind", "kindNs", "kindNsName", and "global" as a good, default set.  Wrote-up the proposal for those in the follow-on Issue, here: https://github.com/defenseunicorns/pepr/issues/1126 .

Hope that covers all our bases. :crossed_fingers:

**Comment by cmwylie19** [comment]
This is passing CI, it fixes the bug. We are also going to introduce a new part of CI that tests against uds run command.

**Review by cmwylie19 — APPROVED** [review]
