### PR TITLE
chore: fix circular dependency between lib.ts and sdk.ts

### LINKED ISSUE #1349: chore: fix circular dependencies between lib.ts and sdk.ts
### Describe what should be investigated or refactored
There is a circular dependency between lib.ts and sdk.ts that should be fixed.

In addition, the duplicate code related to types.ts and mutate-types.ts needs to be resolved.

### PR DESCRIPTION
**Pull request by schaeferka**
## Description
There is a circular dependency between lib.ts and sdk.ts that should be fixed.

In addition, the duplicate code related to types.ts and mutate-types.ts needs to be resolved.
...

End to End Test:    
(See [Pepr Excellent Examples](https://github.com/defenseunicorns/pepr-excellent-examples))

## Related Issue

Fixes #1349 

Relates to #

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Other (security config, docs update, etc)

## Checklist before merging
- [ ] Unit, [Journey](https://github.com/defenseunicorns/pepr/tree/main/journey), [E2E Tests](https://github.com/defenseunicorns/pepr-excellent-examples), [docs](https://github.com/defenseunicorns/pepr/tree/main/docs), [adr](https://github.com/defenseunicorns/pepr/tree/main/adr) added or updated as needed
- [ ] [Contributor Guide Steps](https://docs.pepr.dev/main/contribute/#submitting-a-pull-request) followed

### CODE REVIEW

File: src/lib/types.ts [hunk 1]
```diff
@@ -361,3 +350,33 @@ export interface GroupVersionResource {
   readonly version: string;
   readonly resource: string;
 }
+
+// AdmissionRequest interface for handling admission requests in mutation context
+export interface AdmissionRequest<T = KubernetesObject> {
```
Comment (cmwylie19) [inline src/lib/types.ts]:
```suggestion
Duplicated code ^ mutate-types and types
```

**Review by cmwylie19 — CHANGES_REQUESTED** [review]

**Review by cmwylie19 — APPROVED** [review]
